name = "NEMOTools"
uuid = "05107f91-cac6-4284-93e5-bdda0712134e"
authors = ["Henri Vuollekoski <henri.vuollekoski@fmi.fi> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
